version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"

  postgres:
    build: ./postgres
    environment:
      POSTGRES_DB: projetTp1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  pgadmin:
    build: ./pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
